### ISSUE TITLE
sometimes stuck on isempty function and cache padding

### ISSUE THREAD

**Issue by 69736c616d** [jnk0le/Ring-Buffer#2] opened 2018-08-08 15:07 UTC
again, thank you very much for your effort and sharing. In my tests sometimes isEmpty function consumes too much time (30-50 ms) which is too much for a lock-free queue. Other is a question is there a reason why you dont use cache padding to avoid head-tail ping pong in cache ?

thanks

**Comment by jnk0le** [comment] 2018-08-09 00:25
`isEmpty` function is actually implemented as:
```
bool isEmpty(void) const {
	return (head - tail) == 0;
}
``` 
so the problem might be the other thread that can't keep up, or some sort of caching issues. I need a minimum test case to say something more.

About the second question:
This implementation was targeted for a cache-less and single core embedded cpu's so the proper caching was not a priority and that's why index initialization is still so weird. I'll try to figure out the 'one fits all' solution for a cache ping-pong soon.

**Comment by 69736c616d** [comment] 2018-08-09 12:04
test case is that there is two threads one is writer one is reader. They share lock-free queue, writer thread before remove item from queue it tests emptiness. In that point isEmpty sometimes consumes  much time. 

For cache padding i use -O3 gcc option to pass it to compiler but to be sure  i added 64 bytes of char between head and tail. But problem still continues.

            volatile size_t head;
            char cacheLinePad0[64];
            volatile size_t tail;

Maybe 'volatile' can have side effect to compiler optimization. 

Thanks again

**Comment by jnk0le** [comment] 2018-08-10 16:39
> writer thread before remove item from queue it tests emptiness

That should be correct sequence for the reader.

Do you observe the stalls when using only return statements of `insert`/`remove` functions instead?

**Comment by 69736c616d** [comment] 2018-08-13 09:08
no it works well when i use  only insert / remove operations.

**Comment by jnk0le** [comment] 2018-08-17 00:54
What CPU, and OS are you using and how are you measuring those stalls?

Does a calling `isEmpty` function through a funcion with `noinline` attribute, or setting `wmo_multi_core` template parameter to true, change anything?

**Comment by 69736c616d** [comment] 2018-08-19 21:42
Cpu is intel x64 and OS is Centos 7, i measure it using std::chrono in microsecond precision (logging since epoch).

No i didnt add noinline attribute, I  am using former version which doesnt have wmo_multi_core. I actually added some functions to it, i will send you a PR soon :)   

I am in holiday now, after that I would like to test more, will inform you for results. 

Again thanks for your effort

**Comment by jnk0le** [comment] 2018-08-21 22:21
The problem might also be missing acquire fence, but as i know, x86 is strongly ordered and false sharing should immediately pass those variables around cores.

**Comment by jnk0le** [comment] 2018-09-20 18:01
Added extra memory barriers in https://github.com/jnk0le/Ring-Buffer/commit/d0c1e5f2503f8471e7e17d07f98065bffd1c7850

You need to compile it with `wmo_multi_core` parameter set to make use of them.

**Comment by 69736c616d** [comment] 2018-09-21 07:26
ok, i will test it sorry for delay but i am very busy for release

**Comment by jnk0le** [comment] 2018-09-25 01:06
https://github.com/jnk0le/Ring-Buffer/commit/ce58486f36bde41ee7746f9cbd9b3d111c41d7ed allows to enable padding by setting `cacheline_size` parameter.

**Comment by jnk0le** [comment] 2019-10-09 19:37
Closing as the issue is quite old and stalls in `return (head-tail) == 0` most likely indicate some kind of issue with profiler/inlining.

**Closed as completed by jnk0le** 2019-10-09 19:37 UTC
